# ImageN Jekyll Configuration
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json", "README.md", "Rakefile"]

# Theme
remote_theme: pmarsceill/just-the-docs

# Theme configuration
title: Eclipse ImageN
description: Java Image Processing API
search_enabled: true
aux_links:
    "Version 0.4.0":
     - "https://github.com/eclipse/imagen/tags"
    "Eclipse Project":
      - "https://projects.eclipse.org/projects/technology.imagen"
    "GitHub":
      - "http://github.com/eclipse/imagen"
      
# site configuration

imagen_version: "0.4-SNAPSHOT"

defaults:
 - scope:
     path: "assets/images"
   values:
     image: true